### ISSUE TITLE
值得怀疑的 常见问题解决方案

### ISSUE THREAD

**Issue by SerinaNya** [LittleSkinChina/manual#3]
https://github.com/tnqzh123/littleskin-manual/blob/9bbd4dfdd4c81b4814de13afc390dce5fe3aa5ae/faq.md#L80-L95

实测：若不修改配置文件（`.minecraft\config\skinport.cfg`）中的一些字段，则无效

另附配置文件 [skinport.zip](https://github.com/tnqzh123/littleskin-manual/files/4358992/skinport.zip)：
``` cfg
# Configuration file

client {
    # /skins/(uuid|username) and /capes/(uuid|username) will be queried for respective resources [default: http://example.com]
    S:hostCustomServer=http://example.com

    #  [default: true]
    B:useCrafatar=true

    #  [default: false]
    B:useCustomServer=false

    #  [default: true]
    B:useMojang=true
}


```

要注意的是，我未探索过如何修改才能有效；但我可以确定的是，不修改的话是无效的（注意正版用户重名问题可能导致假象

**Comment by SerinaNya** [comment]
貌似要改 `S:hostCustomServer=http://example.com`

**Comment by SerinaNya** [comment]
@tnqzh123

**Comment by tnqzh123** [comment]
~~淦，Close 错了...~~

Thanks for reporting.

等我有空的时候会联系有关方面进行确认。

**Comment by SerinaNya** [comment]
真有你的

**Comment by SerinaNya** [comment]
linked #14
