### ISSUE TITLE
建议添加：Java 版本注意事项

### ISSUE THREAD

**Issue by SerinaNya** [LittleSkinChina/manual#4]
### Java 版本注意事项
你的 Java 版本必须满足以下中的任何一个条件：
- ≥ 7u111
- ≥ 8u101

否则可能无法识别 Let's Enccrypt 签发的 SSL 证书。

你可以前往 [Java.com](https://www.java.com/) 下载适合你系统的 Java 版本，  
你也可以在 [官方用户交流群](./user-group.html) 的 QQ 群文件中下载到较新版本的 Java。

**Comment by tnqzh123** [comment]
换回 TrustAsia 的证书了。
