### ISSUE TITLE
Microsoft账户验证功能已可以使用

### ISSUE THREAD

**Issue by yangnuozhen** [LittleSkinChina/manual#51]
经过实测，Microsoft账户已经可以用于正版验证，但在帮助文档中的[faq.md](https://manual.littlesk.in/faq.html) 的[无法绑定正版账号？](https://manual.littlesk.in/faq.html#%E6%97%A0%E6%B3%95%E7%BB%91%E5%AE%9A%E6%AD%A3%E7%89%88%E8%B4%A6%E5%8F%B7%EF%BC%9F) 一节却没有更新。

[Link in Github](https://github.com/LittleSkinChina/manual/blob/master/faq.md)

**Comment by gxres042** [comment]
Thanks for your remind.

I will open a Pull Request later, and this suggestion will be included in this Pull Request.

If you find some infomation was not updated next time, you can open a Pull Request to update these infomation.

**Comment by tnqzh123** [comment]
de22f2e
